### PR TITLE
Proper import/export filter

### PR DESCRIPTION
**Pull request by anion155**
Have found the way ts filters declarations. Did replicate it. [Source](https://github.com/microsoft/TypeScript/blob/583edce6b0505e12a4627902147141661ca1b256/src/compiler/transformers/ts.ts#L3051).

### CODE REVIEW

**Comment by danielpza** [comment]
@anion155, these are a lot of changes, care to explain the process?

- why do you need the extensions for? https://github.com/LeDDGroup/typescript-transform-paths/pull/14/files#diff-f41e9d04a45c83f3b6f6e630f10117feR22
- is `updateImportDeclaration` better than just update `node.moduleSpecifier`? It *seems* the proper way to do it, but maybe it isn't worth the hassle.

**Comment by anion155** [comment]
Yep. I really wanted to discuss this, but it's hard to without the code. So it's more like suggestion.

Manually changing text is not really good solution, types-only exports not filtered as in vanilla ts, which makes them stay in result file as import side effects.

So, I did search how this module declarations handled in compiller. As you can see in previous link it is made by transformer, so I just copied filter logic over here.

But I can't keep silent about resolver, it is internal api in ts compiller. It could become a problem in future. But it can be easily guarded.

What if leave imports as is it is now (`.text =`) and make only exports use resolver, only when resolver is available?
About extensions. I needed to check if module exists, and for I used fs.exists for which I needed extensions, project using custom loaders or transformers, which could load not only js modules, but and images and css and anything. So I made extensions customizable. But I recently found about `require.resole` function, so I will probably rewrite this a bit later. It had to be probably in standalone pr.

**Comment by danielpza** [comment]
> What if leave imports as is it is now (`.text =`) and make only exports use resolver, only when resolver is available?

What's the difference between the imports and the exports?

**Comment by anion155** [comment]
Types-only re-export does not getting filtered. In tests/utiles/types-only.ts uncomment throw row and tests will fail, cause this module will be imported at runtime.

**Comment by danielpza** [comment]
Actually that's because of the `*` syntax in `export * from "@utils/types-only";`
```diff
modified   tests/utils/index.ts
@@ -1,3 +1,3 @@
 export * from "@utils/sum";
 export * from "@utils/subs";
-export * from "@utils/types-only";
+export { NoRuntimecodeHere } from "@utils/types-only";
```

changing from `*` to `{ NoRuntimecodeHere }`  fixes the issue, so I guess the problem is not between imports and exports but between `*` and `{ ImplicitImportsExports }`

**Comment by anion155** [comment]
Did not thought about that. Will update pr.

**Comment by anion155** [comment]
I've used previous version of visit and added filter of types-only star re-export declarations. And used `require.resolve` for modules resolving.

**Comment by danielpza** [comment]
@anion155, there are some conflicts with the other branches.

Also, could we keep the output of the tests in a separate directory like before in `out/`, I think it's cleaner that way, what do you think?

**Comment by danielpza** [comment]
@anion155, could you upload the original PR?, github doesn't allow me to fetch a previous commit.

**Comment by danielpza** [comment]
closed in https://github.com/LeDDGroup/typescript-transform-paths/pull/17

**Pull request closed without merging**
