### PR TITLE
fix: Support TS 4+

### LINKED ISSUE #68: typescript v4 support
typescript@4.0.2
typescript-transform-paths@2.0.0

```
typescript-transform-paths/lib/index.js:106
            return updaterFn(typescript_1.default.createLiteral(p));
                   ^
TypeError: typescript_1.default.updateNode is not a function
```

### PR DESCRIPTION
**Pull request by nonara**
Closes #68

### CODE REVIEW

**Comment by nonara** [comment]
Hi @danielpza - Looks like I can't merge it, so I'll leave it to you to do the standard-version bump. (Was I meant to be maintainer?)

This is non-breaking, so it should be fine as a patch bump.

Not for this bump, but would you mind including your prettierrc config to the package so that we can add prettier as a dev dependency `package.json`. This way I can be sure that it's following proper formatting rules.

**Review by danielpza — DISMISSED** [review]

**Comment by danielpza** [comment]
Looks good, great job as always.

> Hi @danielpza - Looks like I can't merge it, so I'll leave it to you to do the standard-version bump. (Was I meant to be maintainer?)

I think I put it so another maintainer has to approve it before merging it, but I'll probably disable that to have more freedom and speed.

> This is non-breaking, so it should be fine as a patch bump.

Yeah, it should be a patch. I'll see if I can give you access to npm too.

> Not for this bump, but would you mind including your prettierrc config to the package so that we can add prettier as a dev dependency package.json? This way we can ensure all changes follow the formatting rules.

Yes will do, I generally use the latest version of prettier, no custom config whatsoever.

**Comment by danielpza** [comment]
@nonara do you want npm publish access too? if so could you send your npm username? And you might as well update the `author` package.json property.

**Comment by danielpza** [comment]
@nonara do you want npm publish access too? if so could you send your npm username? And you might as well update the `author` package.json property.

**Review by danielpza — DISMISSED** [review]

**Comment by nonara** [comment]
> do you want npm publish access too? 

Sure. My username is `nonara`. If you'd like, I can add a publish action that publishes on new tag.

> And you might as well update the `author` package.json property.

I'll switch to `contributors`, so we're both in there. It's nice not being solo for once! 😄

**Comment by danielpza** [comment]
> If you'd like, I can add a publish action that publishes on new tag.

Sure go ahead, honestly I've tried a few times but never got it right :sweat_smile:

**Comment by nonara** [comment]
Will do. It's still requiring approval. Probably just for this PR, so if you want to approve one last time, we'll call this one a wrap, and I'll do a separate commit for the GH action when I can get into npm and get a token. Then I'll push a release.

You just run `npm release` right? No args or any extra steps to create the release with standard-version?

**Review by danielpza — APPROVED** [review]

**Comment by danielpza** [comment]
> You just run npm release right? No args or any extra steps to create the release with standard-version?

Yes, generally:

```sh
npm run release
# check everything is fine
npm publish
git push origin --tags
```

**Comment by nonara** [comment]
Looks like I can't add secrets to the repo. If you want to do the following, I'll add the GH actions script:

1. Grab an auth token from npmjs.com
2. Add it to [Secrets](https://github.com/LeDDGroup/typescript-transform-paths/settings/secrets) under the name `NPM_TOKEN`

And just let me know when it's ready and I'll add the script.

**Comment by nonara** [comment]
Looks like I might still have access issues.

Can't push to master

`
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "continuous-integration/appveyor/pr" is expected. At least 1 approving review is required by reviewers with write access.        
error: failed to push some refs to 'git@github.com:LeDDGroup/typescript-transform-paths.git'
`

**Comment by danielpza** [comment]
> Can't push to master

You should be able now.

> Add it to Secrets under the name NPM_TOKEN

Done

**Comment by nonara** [comment]
Still rejecting 😞

**Comment by danielpza** [comment]
Ok should be fixed now.

**Pull request merged**
