### PR TITLE
feat: provide transformer for NX

### PR DESCRIPTION
**Pull request by zyf0330**

### CODE REVIEW

**Comment by zyf0330** [comment]
@nonara Hello, I want to ask that this plugin does transformer for source code at which phase, `before` or `after`?

**Comment by zyf0330** [comment]
@nonara Hello, do you have any time to see this?

**Comment by nonara** [comment]
Hi @zyf0330 - I apologize for not getting to this on the weekend. I didn't realize that it was Easter, so I'm playing catch up. I am wrapping up another PR review right now and will be going over this one immediately after.

**Comment by nonara** [comment]
This looks pretty good. Thanks for the nice work!

I'd like to see an end-to-end test to make sure that we can track it actually working with nx. That way, in case nx ever changes anything, it will fail out and we can catch it.

Can you add a very basic test project in `test/projects` and make the test do a simple transform test using nx? I would likely build it with `child_process.execSync`. 

For an example, have a look at the `test/projects/extras` project and `test/tests/extras.test.ts` test file.

**Comment by zyf0330** [comment]
> This looks pretty good. Thanks for the nice work!
> 
> I'd like to see an end-to-end test to make sure that we can track it actually working with nx. That way, in case nx ever changes anything, it will fail out and we can catch it.
> 
> Can you add a very basic test project in `test/projects` and make the test do a simple transform test using nx? I would likely build it with `child_process.execSync`.
> 
> For an example, have a look at the `test/projects/extras` project and `test/tests/extras.test.ts` test file.

Ok, I will try

**Comment by zyf0330** [comment]
@nonara Hello, please review my e2e test.
I just test declaration emit, because this is my only need.

**Comment by zyf0330** [comment]
@nonara Do you have any time to review this rencently?

**Comment by zyf0330** [comment]
@nonara Hello, do you have time to see this?

**Comment by nonara** [comment]
Hi @zyf0330 . Sorry for the delay. I've been out for a few months. I will review this shortly!

**Comment by nonara** [comment]
Looks like I don't have write access here, so I pushed to master. Here's the commit:

- https://github.com/LeDDGroup/typescript-transform-paths/commit/66191641bcd023464198b1974a6c351c831dc803

**Comment by zyf0330** [comment]
OK, I am glad you come back finally!

**Pull request closed without merging**
