### PR TITLE
fix: type only imports not deleted

### LINKED ISSUE #48: Importing a mix of types and values in an import using a custom path results in undefined imports in result JavaScript
Given:

file1.ts:
```
export type Foo = 'bar';

export const baz = 'inga'; // ;)
```

file2.ts:
```
import { Foo, baz } from '@custom/scope/file1';

[...]
```

When the code is compiled, the Javascript import will read something like this:

file2.js:
```
import { Foo, baz } from '@custom/scope/file1';
```

but `Foo` will be undefined and cause errors.

### PR DESCRIPTION
**Pull request by danielpza**
It seems to be an issue with the latest version of typescript, the option `isTypeOnly` was not present in previous version and that would cause errors see #48.

### CODE REVIEW

**Comment by DmitryKoterov** [comment]
Unfortunately the effect is still there, here is a minimal repro code:
https://github.com/DmitryKoterov/typescript-transform-paths-bug 

image

after `npx ttsc` (the code of this PR is applied):

image

**Comment by danielpza** [comment]
thanks for confirming @DmitryKoterov, yet I don't think I'll be able to work on this for a while, so anyone is free and welcome to try to tackle this issue

**Comment by dko-slapdash** [comment]
Oh no, hope it’s not related to the pandemic...

Are you keen on accepting pull requests? I think I’ll anyway need to fork a couple of libraries eventually (this one and typescript-is) to implement some missing features.

**Comment by DmitryKoterov** [comment]
Oh no, hope it’s not related to the pandemic...

Are you keen on accepting pull requests? I think I’ll anyway need to fork a couple of libraries eventually (this one and typescript-is) to implement some missing features.

**Comment by danielpza** [comment]
> Oh no, hope it’s not related to the pandemic...

no, it's not related to the pandemic, sorry if it sounded like that, just generally busy with other affairs.

> Are you keen on accepting pull requests? I think I’ll anyway need to fork a couple of libraries eventually (this one and typescript-is) to implement some missing features.

Yeah I'll still be monitoring issues and PRs, and do according testing/merging for PRs.

**Comment by nonara** [comment]
Closing for housekeeping

**Pull request closed without merging**
