### PR TITLE
FIXED: dynamic type imports

### PR DESCRIPTION
**Pull request by hedwiggggg**
Resolve https://github.com/LeDDGroup/typescript-transform-paths/issues/45

### CODE REVIEW

**Comment by danielpza** [comment]
@all-contributors add @hedwiggggg for bug, test, and code

**Comment by hedwiggggg** [comment]
I've tested it myself a little bit;
`ImportTypeNode` is type-only

so this for example won't work:

```
async function main(): Promise<void> {
  const Logger = await (await import('@/test')).Logger;
  console.log(new Logger());
}

main();
```

**Comment by hedwiggggg** [comment]
Okay, I think I could find a pattern to get the corresponding nodes for async imports.

```
    if (ts.isCallExpression(node)) {
      if (node.expression.kind === ts.SyntaxKind.ImportKeyword) {
        console.log(node);
      }
    }
```

Idk, if it's possible to simplify this; Unfortunately it seems to be not as easy as the type-only imports.

**Comment by hedwiggggg** [comment]
It turned out that the pattern is not so different from the require statement detection. I extended the tests and refactored the code a bit.

**Comment by danielpza** [comment]
included in v1.1.14

**Pull request merged**
